import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import Sidebar from "./Components/Sidebar";
import Stylesprovider from "./Providers/Stylesprovider";
import ContextProvider from "./Providers/contenxtProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Stylesprovider>
            <Sidebar />
            {children}
          </Stylesprovider>
        </ContextProvider>
      </body>
    </html>
  );
}